import React from 'react';
import Footer from '../footer';
const Terms = () => {


  return (
    <>
      <section id="policy" className='policy'>
          <h1 className='main-title'>TERMS OF USE</h1>
          <p><strong>Version. </strong>This version of the document is dated February 13, 2025, and comes into force since February 13, 2025. </p>
          <p><strong>We and you. </strong> These Terms of Use (“Terms of Use” or “Terms”) set forth the terms and conditions governing your (“you,” “your,” or “yourself”) use of the 100 Franklins website located at https://100f.com/ (“we”, “us”, “our”, “100 Franklins”) along with any related software, services, and products (collectively, the “Website”). These Terms apply to your use of the Website, including but not limited to:
          </p>
          <p>
          (A) investigating and evaluating potential investment opportunities in the future online platform as an “Investor,” and
          </p>
          <p>
          (B) joining the waiting list to access the platform’s services and features in the future as an “Approved User.”
          </p>
          <p><strong>Approval. </strong> Your use of the Website constitutes your agreement to all of the terms and conditions in these Terms of Use and our Privacy Policy located at <a className="link" href="https:// 100f.com/privacy_policy">100 Franklins Privacy Policy</a>, and we encourage you to read these two documents carefully.</p>
          <div className='important-block'>
              <h2 className="secondary-title">IMPORTANT!</h2>
              <p>
              IF YOU DO NOT AGREE WITH THE TERMS OF THIS DOCUMENT, PLEASE, EXIT THE WEBSITE IMMEDIATELY. PLEASE BE ADVISED THAT YOUR CONTINUED USE OF THE WEBSITE OR THE INFORMATION PROVIDED HEREIN SHALL INDICATE YOUR CONSENT AND AGREEMENT TO THESE TERMS.
              </p>
          </div>

          <p><strong>Revision. </strong>You understand and agree that 100 Franklins may revise, modify, and/or supplement the Terms of Use (the “Revised Terms of Use”) at any time. Any Revised Terms of Use will be effective immediately upon your next entering the Website following the posting of the next version of the Revised Terms - you will see an appropriate pop-up notification once you enter the Website. If you do not agree to the Revised Terms of Use, you must stop using the Website and close your account. You can deactivate your account by emailing us at <a href="mailto:info@100f.com">info@100f.com</a>. By continuing to use the Website following notice, or by failing to deactivate your account, you hereby expressly agree to be bound by the Revised Terms of Use and acknowledge that your continued use of the Website is valid consideration for the Revised Terms of Use. These Terms of Use are valid for the whole period until it is replaced or canceled by its newer version or any other document on the Website, as the case may be.
          </p>
          <p><strong>The Platform. </strong>For the purposes of this document, the Platform means the online platform located at <a className="link" href="https://100f.com/">https://100f.com/</a> which will be the unified platform connecting qualified Web3 projects with a knowledgeable audience. The Platform will be developed by 100 Frankins, deployed instead of the Website and have separate terms of use and privacy policy, which we encourage you to look through after the Platform publication.
          </p>
          <p><strong>Website Eligibility.</strong> To be eligible to use the Website, you represent, warrant and covenant that you: (A) Are eighteen (18) years of age or older; (B) Have full power and authority to enter into the Terms of Use and to be bound by the Terms of Use; (C) Will not violate any other agreement to which you are a party by agreeing to the Terms of Use; (D) Are not restricted from using the Website or similar websites in any way or for any reason; (E) Will only maintain one account at any given time.
          </p>
          <p><strong>The Website is an informational Venue. </strong>The Website offers a venue where users acting as potential Investors can request and obtain individual investment proposal OR acting as potential Approved Users who want to be notified of the launch of the Platform and be one of its first users. The website provides or is the place for providing no services and asks you for no payments. We will contact you directly if you are a potential Investor or will send you a notification if you are an Approved User. By using the Website, you understand and agree that no joint venture, partnership, employment, franchise, or agency relationship exists between you and 100 Franklins or 100 Franklins and any other Website user. The Website has been prepared for informational purposes only and is not intended to be used as a complete source of information on any particular company. You should never invest in the securities or digital assets of any of the companies mentioned on the Website based solely on the information contained there. You should assume that all information provided regarding companies is not trustworthy unless verified by your own independent research</p>
          <p><strong>Test mode and no guarantee. </strong>Please pay attention that the Website is now operating in the test mode, so any bug, error, or technical malfunction may occur. Should you discover any such bug, error or malfunction, notify us thereon by sending e-mail to info@100f.com. You are granted to use the Website operating &quot;as is&quot;. That means you are given no guarantee of Website use, functionality, correctness and meeting of your plans and goals of its use. Pay attention that during the test mode, the Website, its functions, features, speed of its operation, quantity of its users, etc. may change substantially. That being said, You are using the Website at your own discretion and at your own risk. However, you are strictly forbidden to use any prohibited or deleterious software, including viruses or phishing programs, using the Website.</p>
          <p><strong>Users and Approved Users. </strong>Please note, that we reserve the right to deny you to use the Website at our sole discretion, as well as delete your registration data from the Website. Also as for now, we are planning to have a limited quantity of Approved Users, authorised on the Platform hence there is a possibility you will not be granted access to the Platform as the Approved User under our sole decision or due to the fact that other users have been duly authorised themselves on the Platform before you do the same.</p>
          <p><strong>Disclaimer</strong></p>
          <h2 className="secondary-title">DO NOT MAKE ANY INVESTMENT DECISION UPON ANY MATERIALS FOUND ON THIS WEBSITE.</h2>
          <p>Neither 100 Franklins nor any of its affiliates are registered as securities broker-dealers or investment advisers in any jurisdiction or country. We are neither licensed nor qualified to provide investment advice. Information provided on the Website is general in nature and does not constitute financial advice. We do not accept any liability for any error or omission on this website or for any resulting loss or damage suffered by the recipient or any other person. 
          The contents of the Website are not provided to any particular individual with a view toward their individual circumstances. The information contained on the Website is not an offer to buy or sell securities or digital assets. The information contained therein constitutes impersonalized advice and involves disinterested commentary on the securities or digital assets discussed. We do not, through the Website, or otherwise, offer securities, other financial products, or digital assets. We disclaim any liability for loss, damage, cost, or other expenses that you might incur as a result of any information provided on this website.
          Any individual who chooses to invest in any securities or digital assets should do so with caution. Investing in securities and digital assets is speculative and carries a high degree of risk; you may lose some or all of the money that is invested. Always research your own investments and consult with a registered investment advisor or licensed stockbroker in your jurisdiction before investing.
          Information contained on the Website and on the Platform afterwards will contain “forward looking statements” as defined under Section 27A of the Securities Act of 1933 and Section 21B of the Securities Exchange Act of 1934. Users are cautioned not to place undue reliance upon these forward-looking statements. These forward-looking statements are subject to a number of known and unknown risks and uncertainties outside of our control that could cause actual operations or results to differ materially from those anticipated. Factors that could affect performance include, but are not limited to, those factors that are discussed in each company’s most recent reports or registration statements filed with the SEC. You should consider these factors in evaluating the forward-looking statements included on the website and not place undue reliance upon such statements
          </p>
          <p><strong>Legal Statement on the information providing</strong></p>
          <p>While all reasonable care has been taken in providing information via the Website, including analytics articles and/or white papers we create, it should not be construed as being specific to your investment objectives, financial situation, or particular needs. However, We do not provide any assurance as to the accuracy or completeness of the information provided, including information regarding a company’s plans or ability to effect any planned or proposed actions. We have no first-hand knowledge of any company’s operating and therefore cannot comment on their capabilities, intent, resources, nor experience and we make no attempt to do so. Statistical information, currency amounts, and market size data was provided by the subject company and related sources which We believe to be reliable.
          To the fullest extent of the law, We will not be liable to any person or entity for the quality, accuracy, completeness, reliability, or timeliness of the information provided on this website, or for any direct, indirect, consequential, incidental, special or punitive damages that may arise out of the use of information we provide to any person or entity (including, but not limited to, lost profits, loss of opportunities, trading losses, and damages that may result from any inaccuracy or incompleteness of this information).
          Unless otherwise specified, the copyright of information provided on this Website is owned by 100 Franklins, Inc. You may not alter or modify this information in any way, including removing this copyright notice. 
          </p>
          <p><strong>Jurisdiction; Venue. </strong>Any dispute, demand, claim, controversy, cause of action, lawsuit or proceeding (collectively, “Dispute”) arising out of or in any way related to the Website and/or the Terms of Use shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its provisions regarding conflicts of law. You submit to the exclusive jurisdiction of the state and federal courts of Delaware. </p>
          <p><strong>Indemnity. </strong>You agree to defend, indemnify, and hold 100 Franklins harmless from and against any and all Disputes, including without limitation for damages, injuries, losses, liabilities, and reasonable legal and accounting fees (collectively, “Indemnified Claims”), resulting from, or alleged to result from: (A) Your breach of the Terms of Use; (B) Any information and/or content you submit to or transmit through the Website, (C) Your or misuse of the Website including, without limitation, your unauthorized or unlawful use of the Website; (D) Your violation of any applicable law, rule or regulation pertaining to your use of the Website; (E) The use of the Website by any other person using your account. We will use reasonable efforts to provide you with prompt notice of any such Indemnified Claims and may assist you, at our expense and option, in defending any such Indemnified Claims.</p>
          <p><strong>Waiver; Severability. </strong>Failure by 100 Franklins to enforce any provision(s) of the Terms of Use will not be construed as a waiver of any provision or right. The Terms of Use constitute the entire agreement between you and 100 Franklins. If any provision of the Terms of Use is found to be invalid or unenforceable, the remaining provisions will be enforced to the fullest extent possible, and the remaining provisions will remain in full force and effect. The Terms of Use will inure to the benefit of 100 Franklins, its successors, and assigns.</p>
      </section>
      <Footer/>
    </>
  );
};

export default Terms;